spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/sloth_boot_dev?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:1}

logging:
  level:
    root: info
    com.sloth.boot: debug
