# ===== Docker 环境覆盖配置 =====
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

sloth:
  web:
    response-wrapper: false
