<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.sloth.boot</groupId>
        <artifactId>sloth-boot-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../sloth-boot-parent/pom.xml</relativePath>
    </parent>

    <artifactId>sloth-boot-generator</artifactId>
    <name>Sloth Boot Generator</name>
    <description>Sloth Boot 代码生成器，基于 MyBatis-Plus Generator 封装</description>

    <properties>
        <checkstyle.skip>true</checkstyle.skip>
        <spotbugs.skip>true</spotbugs.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.sloth.boot</groupId>
            <artifactId>sloth-boot-common-core</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.velocity</groupId>
            <artifactId>velocity-engine-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
    </dependencies>
</project>
